/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "3Hello World!"
        }
}

fun main() {
    // println(App().greeting)
    generateSequence {
        print("what is your name")
        readLine()
    }.filterNotNull()
        .takeWhile { it != "exit" }
        .forEach { print("hello $it") }
}
