[versions]
kotlin = "2.0.20" # Compiler and plugin version
kotlinx-serialization = "1.7.3" # Library version for kotlinx.serialization-json

[libraries]
guava = { module = "com.google.guava:guava", version = "33.2.1-jre" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.10.3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
