name: Publish Develop Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: |
          ./gradlew test
          ./gradlew assemble

      - name: Create GitHub Release
        id: create_release # Add a unique ID to this step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: develop-latest
          release_name: "Develop Build"
          draft: false
          prerelease: true

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Use the step ID to reference the output
          asset_path: kross/build/distributions/*.zip
          asset_name: develop-latest.zip
          asset_content_type: application/zip
