name: Publish Develop Build

on:
  push:
    branches:
      - develop

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: |
          ./gradlew test
          ./gradlew assemble

      - name: Debug Build Artifacts
        run: ls -alh kross/build/distributions || echo "No files found"


      - name: Delete Existing Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          existing_release=$(gh release view develop-latest --json id --jq '.id' || echo "")
          if [ -n "$existing_release" ]; then
            echo "Deleting existing release..."
            gh release delete develop-latest --yes
          fi
          existing_tag=$(git tag -l develop-latest || echo "")
          if [ -n "$existing_tag" ]; then
            echo "Deleting existing tag..."
            git tag -d develop-latest
            git push origin :refs/tags/develop-latest
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: develop-latest
          release_name: "Develop Build"
          draft: false
          prerelease: true

      - name: Upload Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: kross/build/distributions/*.zip
          asset_name: develop-latest.zip
          asset_content_type: application/zip
