name: PR Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (update the version as per your project)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Run tests
      - name: Run Tests
        run: ./gradlew test

      # Build the distribution zip
      - name: Build Distribution
        run: ./gradlew distZip

      # Upload the zip file as an artifact
      - name: Upload Distribution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: kross/build/distributions/*.zip